title: ePortfolio 
author: Laura Rivella 
email: laura.rivella@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog will take you with me on my journey to pursue an MSc in Cybersecurity.
  Let's dive in!

theme: jekyll-theme-cayman

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  laurarivella

show_excerpts: true # set to false to remove excerpts on the homepage

defaults:
  - scope:
      path: ""
    values:
      layout: default
